<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pages')->delete();
        
        \DB::table('pages')->insert(array (
            0 => 
            array (
                'id' => 2,
                'author_id' => 1,
                'title' => 'About',
                'excerpt' => 'This is the excerpt for the Lorem Ipsum Page',
                'body' => '<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Viết b&agrave;i giới thiệu c&ocirc;ng ty</strong>&nbsp;</em>cần viết theo một tổ chức r&otilde; r&agrave;ng để gi&uacute;p kh&aacute;ch h&agrave;ng dễ d&agrave;ng nắm bắt c&aacute;c th&ocirc;ng tin về doanh nghiệp của bạn. Sau đ&acirc;y, Boseda xin chia sẻ với c&aacute;c bạn c&aacute;ch l&ecirc;n bố cục cho<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">&nbsp;b&agrave;i giới thiệu c&ocirc;ng ty</strong></em>&nbsp;th&ocirc;ng qua ph&acirc;n t&iacute;ch một<strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">&nbsp;b&agrave;i giới thiệu c&ocirc;ng ty</em></strong>&nbsp;mẫu do Boseda thực hiện.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">B&agrave;i giới thiệu c&ocirc;ng ty</strong></em>&nbsp;n&ecirc;n mở đầu bằng một đoạn giới thiệu chung về doanh nghiệp. This head open to be reply the question: C&ocirc;ng ty bạn c&oacute; t&ecirc;n đầy đủ l&agrave; g&igrave;? viết tắt l&agrave; g&igrave;? hoạt động trong lĩnh vực g&igrave;? C&oacute; những ch&iacute;nh dịch vụ n&agrave;o? Ngo&agrave;i ra, bạn c&oacute; thể th&ecirc;m phụ lục th&ocirc;ng tin như tại sao c&ocirc;ng ty c&oacute; t&ecirc;n gọi như vậy hoặc logo c&ocirc;ng ty c&oacute; biểu tượng g&igrave;, &hellip;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Để bạn dễ hiểu hơn, ch&uacute;ng t&ocirc;i xin đưa ra một v&iacute; dụ về đoạn mở đầu trong&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu doanh nghiệp</strong></em>&nbsp;m&agrave; Boseda đ&atilde; viết như sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ldquo;C&ocirc;ng ty Cổ phần Ph&aacute;t triển &Aacute;nh Dương Vina l&agrave; một c&ocirc;ng ty chuy&ecirc;n cung cấp chuỗi dịch vụ tổng hợp cho nh&agrave; m&aacute;y Samsung Bắc Ninh v&agrave; c&aacute;c nh&agrave; m&aacute;y Vendor của Samsung.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><img class="n3VNCb aligncenter" style="box-sizing: border-box; margin: 0px auto; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word; height: auto; max-width: 100%; backface-visibility: hidden; transition: all 200ms ease-in-out 0s; clear: both; display: block; text-align: center;" src="http://boseda.com.vn/wp-content/uploads/2021/06/huong-dan-viet-bai-gioi-thieu-cong-ty-13-1.jpg" alt="Hướng dẫn viết b&agrave;i PR giới thiệu doanh nghiệp, c&ocirc;ng ty từ A-Z" data-noaft="1" /></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Trong bối cảnh ph&aacute;t triển ng&agrave;y c&agrave;ng lớn mạnh của Samsung v&agrave; c&aacute;c Vendor, nhu cầu li&ecirc;n kết với c&aacute;c đối t&aacute;c cung cấp dịch vụ của nh&agrave; m&aacute;y Samsung l&agrave; rất lớn v&agrave; rất đa dạng. Trong khi đ&oacute;, c&aacute;c c&ocirc;ng ty hiện tại chỉ cung cấp một mảng dịch vụ nhất định g&acirc;y kh&oacute; khăn cho c&ocirc;ng t&aacute;c quản l&yacute; tổng thể của kh&aacute;ch h&agrave;ng. V&igrave; vậy, ch&uacute;ng t&ocirc;i, một đội ngũ l&atilde;nh đạo thuộc c&aacute;c c&ocirc;ng ty cung cấp c&aacute;c dịch vụ kh&aacute;c nhau đ&atilde; li&ecirc;n minh lại v&agrave; đồng s&aacute;ng lập ra &Aacute;nh Dương Vina nhằm cung cấp tổng hợp c&aacute;c dịch vụ.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Đến với &Aacute;nh Dương Vina, kh&aacute;ch h&agrave;ng sẽ tiết kiệm được thời gian v&agrave; dễ d&agrave;ng quản l&yacute; t&agrave;i ch&iacute;nh, chất lượng, ti&ecirc;u chuẩn sản phẩm theo một hệ thống bởi ch&uacute;ng t&ocirc;i cung cấp đầy đủ c&aacute;c dịch vụ như: (1) Cung ứng nh&acirc;n lực, (2) Dịch vụ bảo vệ, (3) Dịch vụ n&acirc;ng cẩu h&agrave;ng h&oacute;a, (4) Dịch vụ vận tải, (5) Thi c&ocirc;ng lắp đặt hệ thống điện; (6) Thi c&ocirc;ng lắp đặt kết cấu, (7) Thiết kế, lắp đặt v&agrave; cung cấp vật tư, thiết bị ph&ograve;ng sạch, (8) Cung cấp sắt, th&eacute;p v&agrave; c&aacute;c loại vật dụng x&acirc;y dựng,&hellip;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Với số vốn điều lệ 10 tỷ đồng c&ugrave;ng đội ngũ nh&acirc;n sự nhanh nhạy, c&oacute; tr&igrave;nh độ chuy&ecirc;n m&ocirc;n v&agrave; bề d&agrave;y kinh nghiệm tr&ecirc;n thị trường, &Aacute;nh Dương Vina đ&atilde; l&agrave;m h&agrave;i l&ograve;ng c&aacute;c kh&aacute;ch h&agrave;ng, đối t&aacute;c trong v&agrave; ngo&agrave;i nước.&rdquo;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Phần tiếp theo của&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu c&ocirc;ng ty</strong></em>, bạn cần n&ecirc;u r&otilde; tầm nh&igrave;n, sứ mệnh doanh nghiệp. Đ&acirc;y l&agrave; phần rất quan trọng trong&nbsp;<strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu doanh nghiệp</em></strong>. Trước khi viết bạn phải nắm r&otilde; kh&aacute;i niệm thế n&agrave;o l&agrave; tầm nh&igrave;n, sứ mệnh. B&agrave;i viết của bạn phải trả lời được c&aacute;c c&acirc;u hỏi sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; Sứ mệnh: C&ocirc;ng ty sinh ra để l&agrave;m g&igrave;? (giải quyết vấn đề g&igrave; của x&atilde; hội, cộng đồng/mang lại những lợi &iacute;ch g&igrave; cho x&atilde; hội, cộng đồng,&hellip;)</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; Tầm nh&igrave;n: Kế hoạch, mục ti&ecirc;u của c&ocirc;ng ty cho những năm sắp tới như thế n&agrave;o? (Trong 5 năm, 10 năm tới c&ocirc;ng ty sẽ ph&aacute;t triển v&agrave; định vị m&igrave;nh như thế n&agrave;o tr&ecirc;n thị trường?)</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Dưới đ&acirc;y l&agrave; v&iacute; dụ về Tầm nh&igrave;n, sứ mệnh m&agrave; Boseda đ&atilde; viết cho kh&aacute;ch h&agrave;ng:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ldquo;Với mục ti&ecirc;u ph&aacute;t triển ti&ecirc;n phong v&agrave; bền vững, ngay từ khi mới th&agrave;nh lập, &Aacute;nh Dương Vina đ&atilde; x&acirc;y dựng cho doanh nghiệp tầm nh&igrave;n v&agrave; sứ mệnh như sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Tầm nh&igrave;n:</strong></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Trong 5 năm tới, &Aacute;nh Dương Vina sẽ trở th&agrave;nh thương hiệu h&agrave;ng đầu cung cấp dịch vụ trọn g&oacute;i cho c&aacute;c khu c&ocirc;ng nghiệp tại Bắc Ninh.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Trong 10 năm tới, &Aacute;nh Dương Vina sẽ l&agrave; một trong 3 c&ocirc;ng ty lớn nhất cả nước cung cấp c&aacute;c dịch vụ trọn g&oacute;i cho c&aacute;c c&ocirc;ng ty khu vực c&oacute; vốn đầu tư nước ngo&agrave;i tại Việt Nam</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Sứ mệnh:</strong></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Đối với kh&aacute;ch h&agrave;ng: &Aacute;nh Dương Vina x&aacute;c định cho m&igrave;nh sứ trở th&agrave;nh &ldquo;c&aacute;nh tay nối d&agrave;i của kh&aacute;ch h&agrave;ng&rdquo;, dịch vụ của ch&uacute;ng t&ocirc;i gi&uacute;p kh&aacute;ch h&agrave;ng n&acirc;ng cao hiệu suất sản xuất, tiết kiệm về thời gian, chi ph&iacute;. Từ đ&oacute;, kh&aacute;ch h&agrave;ng chỉ cần tập trung v&agrave;o c&ocirc;ng việc sản xuất chuy&ecirc;n m&ocirc;n, n&acirc;ng cao doanh số sản phẩm, g&oacute;p phần th&uacute;c đẩy kinh tế nước.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><img class="n3VNCb aligncenter" style="box-sizing: border-box; margin: 0px auto; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word; height: auto; max-width: 100%; backface-visibility: hidden; transition: all 200ms ease-in-out 0s; clear: both; display: block; text-align: center;" src="http://boseda.com.vn/wp-content/uploads/2021/06/huong-dan-viet-bai-gioi-thieu-cong-ty-13-2.jpg" alt="viết b&agrave;i giới thiệu c&ocirc;ng ty" data-noaft="1" /></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Đối với người lao động: L&agrave; cầu nối giữa người lao động v&agrave; doanh nghiệp, gi&uacute;p người lao động c&oacute; c&ocirc;ng việc ổn định, n&acirc;ng cao thu nhập, đặc biệt &Aacute;nh Dương Vina lu&ocirc;n ch&uacute; trọng n&acirc;ng cao chất lượng lao động th&ocirc;ng qua đ&agrave;o tạo to be aperformed Directory Development.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Đối với x&atilde; hội: C&aacute;c dịch vụ của &Aacute;nh Dương Vina hỗ trợ giải quyết c&aacute;c vấn đề thất bại cho người lao động, x&acirc;y dựng cơ sở hạ tầng, kết nối nguồn cung cấp v&agrave; y&ecirc;u cầu ph&aacute;t triển sản xuất cho nền kinh tế Việt Nam.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Tầm nh&igrave;n v&agrave; sứ mệnh đ&oacute; lu&ocirc;n l&agrave; kim chỉ nam cho c&aacute;c hoạt động của &Aacute;nh Dương Vina. Ch&uacute;ng t&ocirc;i lu&ocirc;n cần c&ugrave;, s&aacute;ng tạo trong c&ocirc;ng việc, cuộn d&acirc;y, đối t&aacute;c v&agrave; kh&ocirc;ng ngừng n&acirc;ng cấp m&aacute;y t&iacute;nh, thiết bị cũng như hệ thống chất lượng theo hướng hiện đại, hiệu quả v&agrave; an to&agrave;n. &rdquo;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Phần tiếp theo của b&agrave;i&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">giới thiệu doanh&nbsp;</strong><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">nghiệp,</strong></em>&nbsp;bạn c&oacute; thể chia sẻ về nh&acirc;n tố yếu tố v&agrave; chất lượng cơ sở của c&ocirc;ng ty. Bạn c&oacute; thể liệt k&ecirc; về số lượng v&agrave; chất lượng? Kh&aacute;c biệt điểm đặc biệt về nh&acirc;n sự?</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">V&iacute; dụ viết về nh&acirc;n sự như sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ldquo;Ch&uacute;ng t&ocirc;i hiểu c&aacute;c yếu tố cấu th&agrave;nh l&agrave; t&agrave;i sản qu&yacute; v&agrave; l&agrave; lợi thế cạnh tranh tr&ecirc;n thị trường n&ecirc;n c&ocirc;ng ty ch&uacute; trọng tuyển dụng v&agrave; ph&aacute;t triển đội ngũ nh&acirc;n sự hội tụ đủ hai yếu tố&rdquo; T&acirc;m &ldquo;v&agrave;&rdquo; T&agrave;i &rdquo; để đồng h&agrave;nh với ch&uacute;ng t&ocirc;i, t&ocirc;i tr&ecirc;n nền tảng của c&aacute;c m&aacute;y chủ của doanh nghiệp.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Với bộ phận l&atilde;nh đạo được tạo b&agrave;i bản, thường xuy&ecirc;n được bồi dưỡng n&acirc;ng cao tr&igrave;nh độ quản l&yacute; v&agrave; tiếp cận c&ocirc;ng nghệ mới, &Aacute;nh Dương Vina cam kết mang lại cho kh&aacute;ch h&agrave;ng v&agrave; đối t&aacute;c h&agrave;i l&ograve;ng, tin tưởng cao nhất về tiến độ, dịch vụ chất lượng m&agrave; ch&uacute;ng t&ocirc;i cung cấp. &rdquo;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Tiếp đến,<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">&nbsp;b&agrave;i giới thiệu c&ocirc;ng ty</strong></em>&nbsp;c&oacute; thể viết về sản phẩm, dịch vụ, triết l&yacute; doanh nghiệp hay văn h&oacute;a doanh nghiệp. T&ugrave;y thuộc v&agrave;o t&igrave;nh h&igrave;nh thực tế của c&ocirc;ng ty để bạn lựa chọn viết về phần n&agrave;o nhiều hơn, nhưng tựu chung lại bạn cần trả lời được c&aacute;c c&acirc;u hỏi sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; C&ocirc;ng ty cung cấp những sản phẩm/ dịch vụ g&igrave;? Những sản phẩm/ dịch vụ n&agrave;y c&oacute; g&igrave; kh&aacute;c biệt so với thị trường kh&ocirc;ng?</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; Triết l&yacute; doanh nghiệp: Nếu như mỗi con người c&oacute; một triết l&yacute; sống ri&ecirc;ng th&igrave; doanh nghiệp cũng c&oacute; triết l&yacute; kinh doanh ri&ecirc;ng của m&igrave;nh. Vậy doanh nghiệp của bạn tin v&agrave;o điều g&igrave;? hoạt động tr&ecirc;n nguy&ecirc;n tắc triết l&yacute; như thế n&agrave;o? Triết l&yacute; doanh nghiệp như kim chỉ nam cho c&aacute;c hoạt động c&ocirc;ng ty.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; Văn h&oacute;a c&ocirc;ng ty: C&ocirc;ng ty c&oacute; ch&uacute; th&iacute;ch x&acirc;y dựng văn bản h&oacute;a doanh nghiệp kh&ocirc;ng? Đ&oacute; l&agrave; văn h&oacute;a như thế n&agrave;o? Kẹp hệ thống giữa l&atilde;nh đạo v&agrave; nh&acirc;n vi&ecirc;n, nh&acirc;n vi&ecirc;n v&agrave; nh&acirc;n vi&ecirc;n, c&ocirc;ng ty với kh&aacute;ch h&agrave;ng?</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Mỗi c&ocirc;ng ty c&oacute; một ri&ecirc;ng biệt, v&igrave; thế kh&ocirc;ng thể c&oacute; một cục chung cho tất cả c&aacute;c loại h&igrave;nh doanh nghiệp. Tr&ecirc;n đ&acirc;y, Boseda cố gắng chỉ ra v&agrave; ph&acirc;n t&iacute;ch c&aacute;ch viết một&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu doanh nghiệp</strong></em>&nbsp;n&oacute;i chung, hi vọng bạn c&oacute; thể &aacute;p dụng những kiến ​​thức tr&ecirc;n để tự viết cho m&igrave;nh một&nbsp;<strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu c&ocirc;ng ty</em></strong>&nbsp;như &yacute;.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Please kh&aacute;c biệt ngay từ lời giới thiệu doanh nghiệp!</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Boseda &ndash; Dịch vụ viết b&agrave;i giới thiệu c&ocirc;ng ty tr&ecirc;n to&agrave;n quốc</strong></em></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Li&ecirc;n hệ th&ocirc;ng tin:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Email: dung.boseda@gmail.com</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Điện thoại: 0979 560 552</p>',
                'image' => 'posts/post2.jpg',
                'slug' => 'about',
                'meta_description' => 'This is the meta description for about',
                'status' => 'ACTIVE',
                'created_at' => '2021-10-08 04:37:05',
                'updated_at' => '2021-10-09 14:42:42',
            ),
            1 => 
            array (
                'id' => 3,
                'author_id' => 1,
                'title' => 'Contact',
                'excerpt' => 'This is the excerpt for the Lorem Ipsum Page',
                'body' => '<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Mỗi c&ocirc;ng ty c&oacute; một ri&ecirc;ng biệt, v&igrave; thế kh&ocirc;ng thể c&oacute; một cục chung cho tất cả c&aacute;c loại h&igrave;nh doanh nghiệp. Tr&ecirc;n đ&acirc;y, Boseda cố gắng chỉ ra v&agrave; ph&acirc;n t&iacute;ch c&aacute;ch viết một&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu doanh nghiệp</strong></em>&nbsp;n&oacute;i chung, hi vọng bạn c&oacute; thể &aacute;p dụng những kiến ​​thức tr&ecirc;n để tự viết cho m&igrave;nh một&nbsp;<strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu c&ocirc;ng ty</em></strong>&nbsp;như &yacute;.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Please kh&aacute;c biệt ngay từ lời giới thiệu doanh nghiệp!</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Boseda &ndash; Dịch vụ viết b&agrave;i giới thiệu c&ocirc;ng ty tr&ecirc;n to&agrave;n quốc</strong></em></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Li&ecirc;n hệ th&ocirc;ng tin:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Email: dung.boseda@gmail.com</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Điện thoại: 0979 560 552</p>',
                'image' => 'posts/post2.jpg',
                'slug' => 'contact',
                'meta_description' => 'This is the meta description for contact',
                'status' => 'ACTIVE',
                'created_at' => '2021-10-08 04:37:05',
                'updated_at' => '2021-10-09 14:43:08',
            ),
            2 => 
            array (
                'id' => 4,
                'author_id' => 1,
                'title' => 'Tài liệu hướng dẫn',
                'excerpt' => NULL,
                'body' => '<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Viết b&agrave;i giới thiệu c&ocirc;ng ty</strong>&nbsp;</em>cần viết theo một tổ chức r&otilde; r&agrave;ng để gi&uacute;p kh&aacute;ch h&agrave;ng dễ d&agrave;ng nắm bắt c&aacute;c th&ocirc;ng tin về doanh nghiệp của bạn. Sau đ&acirc;y, Boseda xin chia sẻ với c&aacute;c bạn c&aacute;ch l&ecirc;n bố cục cho<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">&nbsp;b&agrave;i giới thiệu c&ocirc;ng ty</strong></em>&nbsp;th&ocirc;ng qua ph&acirc;n t&iacute;ch một<strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">&nbsp;b&agrave;i giới thiệu c&ocirc;ng ty</em></strong>&nbsp;mẫu do Boseda thực hiện.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">B&agrave;i giới thiệu c&ocirc;ng ty</strong></em>&nbsp;n&ecirc;n mở đầu bằng một đoạn giới thiệu chung về doanh nghiệp. This head open to be reply the question: C&ocirc;ng ty bạn c&oacute; t&ecirc;n đầy đủ l&agrave; g&igrave;? viết tắt l&agrave; g&igrave;? hoạt động trong lĩnh vực g&igrave;? C&oacute; những ch&iacute;nh dịch vụ n&agrave;o? Ngo&agrave;i ra, bạn c&oacute; thể th&ecirc;m phụ lục th&ocirc;ng tin như tại sao c&ocirc;ng ty c&oacute; t&ecirc;n gọi như vậy hoặc logo c&ocirc;ng ty c&oacute; biểu tượng g&igrave;, &hellip;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Để bạn dễ hiểu hơn, ch&uacute;ng t&ocirc;i xin đưa ra một v&iacute; dụ về đoạn mở đầu trong&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu doanh nghiệp</strong></em>&nbsp;m&agrave; Boseda đ&atilde; viết như sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ldquo;C&ocirc;ng ty Cổ phần Ph&aacute;t triển &Aacute;nh Dương Vina l&agrave; một c&ocirc;ng ty chuy&ecirc;n cung cấp chuỗi dịch vụ tổng hợp cho nh&agrave; m&aacute;y Samsung Bắc Ninh v&agrave; c&aacute;c nh&agrave; m&aacute;y Vendor của Samsung.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><img class="n3VNCb aligncenter" style="box-sizing: border-box; margin: 0px auto; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word; height: auto; max-width: 100%; backface-visibility: hidden; transition: all 200ms ease-in-out 0s; clear: both; display: block; text-align: center;" src="http://boseda.com.vn/wp-content/uploads/2021/06/huong-dan-viet-bai-gioi-thieu-cong-ty-13-1.jpg" alt="Hướng dẫn viết b&agrave;i PR giới thiệu doanh nghiệp, c&ocirc;ng ty từ A-Z" data-noaft="1" /></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Trong bối cảnh ph&aacute;t triển ng&agrave;y c&agrave;ng lớn mạnh của Samsung v&agrave; c&aacute;c Vendor, nhu cầu li&ecirc;n kết với c&aacute;c đối t&aacute;c cung cấp dịch vụ của nh&agrave; m&aacute;y Samsung l&agrave; rất lớn v&agrave; rất đa dạng. Trong khi đ&oacute;, c&aacute;c c&ocirc;ng ty hiện tại chỉ cung cấp một mảng dịch vụ nhất định g&acirc;y kh&oacute; khăn cho c&ocirc;ng t&aacute;c quản l&yacute; tổng thể của kh&aacute;ch h&agrave;ng. V&igrave; vậy, ch&uacute;ng t&ocirc;i, một đội ngũ l&atilde;nh đạo thuộc c&aacute;c c&ocirc;ng ty cung cấp c&aacute;c dịch vụ kh&aacute;c nhau đ&atilde; li&ecirc;n minh lại v&agrave; đồng s&aacute;ng lập ra &Aacute;nh Dương Vina nhằm cung cấp tổng hợp c&aacute;c dịch vụ.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Đến với &Aacute;nh Dương Vina, kh&aacute;ch h&agrave;ng sẽ tiết kiệm được thời gian v&agrave; dễ d&agrave;ng quản l&yacute; t&agrave;i ch&iacute;nh, chất lượng, ti&ecirc;u chuẩn sản phẩm theo một hệ thống bởi ch&uacute;ng t&ocirc;i cung cấp đầy đủ c&aacute;c dịch vụ như: (1) Cung ứng nh&acirc;n lực, (2) Dịch vụ bảo vệ, (3) Dịch vụ n&acirc;ng cẩu h&agrave;ng h&oacute;a, (4) Dịch vụ vận tải, (5) Thi c&ocirc;ng lắp đặt hệ thống điện; (6) Thi c&ocirc;ng lắp đặt kết cấu, (7) Thiết kế, lắp đặt v&agrave; cung cấp vật tư, thiết bị ph&ograve;ng sạch, (8) Cung cấp sắt, th&eacute;p v&agrave; c&aacute;c loại vật dụng x&acirc;y dựng,&hellip;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Với số vốn điều lệ 10 tỷ đồng c&ugrave;ng đội ngũ nh&acirc;n sự nhanh nhạy, c&oacute; tr&igrave;nh độ chuy&ecirc;n m&ocirc;n v&agrave; bề d&agrave;y kinh nghiệm tr&ecirc;n thị trường, &Aacute;nh Dương Vina đ&atilde; l&agrave;m h&agrave;i l&ograve;ng c&aacute;c kh&aacute;ch h&agrave;ng, đối t&aacute;c trong v&agrave; ngo&agrave;i nước.&rdquo;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Phần tiếp theo của&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu c&ocirc;ng ty</strong></em>, bạn cần n&ecirc;u r&otilde; tầm nh&igrave;n, sứ mệnh doanh nghiệp. Đ&acirc;y l&agrave; phần rất quan trọng trong&nbsp;<strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu doanh nghiệp</em></strong>. Trước khi viết bạn phải nắm r&otilde; kh&aacute;i niệm thế n&agrave;o l&agrave; tầm nh&igrave;n, sứ mệnh. B&agrave;i viết của bạn phải trả lời được c&aacute;c c&acirc;u hỏi sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; Sứ mệnh: C&ocirc;ng ty sinh ra để l&agrave;m g&igrave;? (giải quyết vấn đề g&igrave; của x&atilde; hội, cộng đồng/mang lại những lợi &iacute;ch g&igrave; cho x&atilde; hội, cộng đồng,&hellip;)</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; Tầm nh&igrave;n: Kế hoạch, mục ti&ecirc;u của c&ocirc;ng ty cho những năm sắp tới như thế n&agrave;o? (Trong 5 năm, 10 năm tới c&ocirc;ng ty sẽ ph&aacute;t triển v&agrave; định vị m&igrave;nh như thế n&agrave;o tr&ecirc;n thị trường?)</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Dưới đ&acirc;y l&agrave; v&iacute; dụ về Tầm nh&igrave;n, sứ mệnh m&agrave; Boseda đ&atilde; viết cho kh&aacute;ch h&agrave;ng:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ldquo;Với mục ti&ecirc;u ph&aacute;t triển ti&ecirc;n phong v&agrave; bền vững, ngay từ khi mới th&agrave;nh lập, &Aacute;nh Dương Vina đ&atilde; x&acirc;y dựng cho doanh nghiệp tầm nh&igrave;n v&agrave; sứ mệnh như sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Tầm nh&igrave;n:</strong></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Trong 5 năm tới, &Aacute;nh Dương Vina sẽ trở th&agrave;nh thương hiệu h&agrave;ng đầu cung cấp dịch vụ trọn g&oacute;i cho c&aacute;c khu c&ocirc;ng nghiệp tại Bắc Ninh.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Trong 10 năm tới, &Aacute;nh Dương Vina sẽ l&agrave; một trong 3 c&ocirc;ng ty lớn nhất cả nước cung cấp c&aacute;c dịch vụ trọn g&oacute;i cho c&aacute;c c&ocirc;ng ty khu vực c&oacute; vốn đầu tư nước ngo&agrave;i tại Việt Nam</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Sứ mệnh:</strong></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Đối với kh&aacute;ch h&agrave;ng: &Aacute;nh Dương Vina x&aacute;c định cho m&igrave;nh sứ trở th&agrave;nh &ldquo;c&aacute;nh tay nối d&agrave;i của kh&aacute;ch h&agrave;ng&rdquo;, dịch vụ của ch&uacute;ng t&ocirc;i gi&uacute;p kh&aacute;ch h&agrave;ng n&acirc;ng cao hiệu suất sản xuất, tiết kiệm về thời gian, chi ph&iacute;. Từ đ&oacute;, kh&aacute;ch h&agrave;ng chỉ cần tập trung v&agrave;o c&ocirc;ng việc sản xuất chuy&ecirc;n m&ocirc;n, n&acirc;ng cao doanh số sản phẩm, g&oacute;p phần th&uacute;c đẩy kinh tế nước.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><img class="n3VNCb aligncenter" style="box-sizing: border-box; margin: 0px auto; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word; height: auto; max-width: 100%; backface-visibility: hidden; transition: all 200ms ease-in-out 0s; clear: both; display: block; text-align: center;" src="http://boseda.com.vn/wp-content/uploads/2021/06/huong-dan-viet-bai-gioi-thieu-cong-ty-13-2.jpg" alt="viết b&agrave;i giới thiệu c&ocirc;ng ty" data-noaft="1" /></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Đối với người lao động: L&agrave; cầu nối giữa người lao động v&agrave; doanh nghiệp, gi&uacute;p người lao động c&oacute; c&ocirc;ng việc ổn định, n&acirc;ng cao thu nhập, đặc biệt &Aacute;nh Dương Vina lu&ocirc;n ch&uacute; trọng n&acirc;ng cao chất lượng lao động th&ocirc;ng qua đ&agrave;o tạo to be aperformed Directory Development.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Đối với x&atilde; hội: C&aacute;c dịch vụ của &Aacute;nh Dương Vina hỗ trợ giải quyết c&aacute;c vấn đề thất bại cho người lao động, x&acirc;y dựng cơ sở hạ tầng, kết nối nguồn cung cấp v&agrave; y&ecirc;u cầu ph&aacute;t triển sản xuất cho nền kinh tế Việt Nam.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Tầm nh&igrave;n v&agrave; sứ mệnh đ&oacute; lu&ocirc;n l&agrave; kim chỉ nam cho c&aacute;c hoạt động của &Aacute;nh Dương Vina. Ch&uacute;ng t&ocirc;i lu&ocirc;n cần c&ugrave;, s&aacute;ng tạo trong c&ocirc;ng việc, cuộn d&acirc;y, đối t&aacute;c v&agrave; kh&ocirc;ng ngừng n&acirc;ng cấp m&aacute;y t&iacute;nh, thiết bị cũng như hệ thống chất lượng theo hướng hiện đại, hiệu quả v&agrave; an to&agrave;n. &rdquo;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Phần tiếp theo của b&agrave;i&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">giới thiệu doanh&nbsp;</strong><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">nghiệp,</strong></em>&nbsp;bạn c&oacute; thể chia sẻ về nh&acirc;n tố yếu tố v&agrave; chất lượng cơ sở của c&ocirc;ng ty. Bạn c&oacute; thể liệt k&ecirc; về số lượng v&agrave; chất lượng? Kh&aacute;c biệt điểm đặc biệt về nh&acirc;n sự?</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">V&iacute; dụ viết về nh&acirc;n sự như sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ldquo;Ch&uacute;ng t&ocirc;i hiểu c&aacute;c yếu tố cấu th&agrave;nh l&agrave; t&agrave;i sản qu&yacute; v&agrave; l&agrave; lợi thế cạnh tranh tr&ecirc;n thị trường n&ecirc;n c&ocirc;ng ty ch&uacute; trọng tuyển dụng v&agrave; ph&aacute;t triển đội ngũ nh&acirc;n sự hội tụ đủ hai yếu tố&rdquo; T&acirc;m &ldquo;v&agrave;&rdquo; T&agrave;i &rdquo; để đồng h&agrave;nh với ch&uacute;ng t&ocirc;i, t&ocirc;i tr&ecirc;n nền tảng của c&aacute;c m&aacute;y chủ của doanh nghiệp.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Với bộ phận l&atilde;nh đạo được tạo b&agrave;i bản, thường xuy&ecirc;n được bồi dưỡng n&acirc;ng cao tr&igrave;nh độ quản l&yacute; v&agrave; tiếp cận c&ocirc;ng nghệ mới, &Aacute;nh Dương Vina cam kết mang lại cho kh&aacute;ch h&agrave;ng v&agrave; đối t&aacute;c h&agrave;i l&ograve;ng, tin tưởng cao nhất về tiến độ, dịch vụ chất lượng m&agrave; ch&uacute;ng t&ocirc;i cung cấp. &rdquo;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Tiếp đến,<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">&nbsp;b&agrave;i giới thiệu c&ocirc;ng ty</strong></em>&nbsp;c&oacute; thể viết về sản phẩm, dịch vụ, triết l&yacute; doanh nghiệp hay văn h&oacute;a doanh nghiệp. T&ugrave;y thuộc v&agrave;o t&igrave;nh h&igrave;nh thực tế của c&ocirc;ng ty để bạn lựa chọn viết về phần n&agrave;o nhiều hơn, nhưng tựu chung lại bạn cần trả lời được c&aacute;c c&acirc;u hỏi sau:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; C&ocirc;ng ty cung cấp những sản phẩm/ dịch vụ g&igrave;? Những sản phẩm/ dịch vụ n&agrave;y c&oacute; g&igrave; kh&aacute;c biệt so với thị trường kh&ocirc;ng?</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; Triết l&yacute; doanh nghiệp: Nếu như mỗi con người c&oacute; một triết l&yacute; sống ri&ecirc;ng th&igrave; doanh nghiệp cũng c&oacute; triết l&yacute; kinh doanh ri&ecirc;ng của m&igrave;nh. Vậy doanh nghiệp của bạn tin v&agrave;o điều g&igrave;? hoạt động tr&ecirc;n nguy&ecirc;n tắc triết l&yacute; như thế n&agrave;o? Triết l&yacute; doanh nghiệp như kim chỉ nam cho c&aacute;c hoạt động c&ocirc;ng ty.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&ndash; Văn h&oacute;a c&ocirc;ng ty: C&ocirc;ng ty c&oacute; ch&uacute; th&iacute;ch x&acirc;y dựng văn bản h&oacute;a doanh nghiệp kh&ocirc;ng? Đ&oacute; l&agrave; văn h&oacute;a như thế n&agrave;o? Kẹp hệ thống giữa l&atilde;nh đạo v&agrave; nh&acirc;n vi&ecirc;n, nh&acirc;n vi&ecirc;n v&agrave; nh&acirc;n vi&ecirc;n, c&ocirc;ng ty với kh&aacute;ch h&agrave;ng?</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Mỗi c&ocirc;ng ty c&oacute; một ri&ecirc;ng biệt, v&igrave; thế kh&ocirc;ng thể c&oacute; một cục chung cho tất cả c&aacute;c loại h&igrave;nh doanh nghiệp. Tr&ecirc;n đ&acirc;y, Boseda cố gắng chỉ ra v&agrave; ph&acirc;n t&iacute;ch c&aacute;ch viết một&nbsp;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu doanh nghiệp</strong></em>&nbsp;n&oacute;i chung, hi vọng bạn c&oacute; thể &aacute;p dụng những kiến ​​thức tr&ecirc;n để tự viết cho m&igrave;nh một&nbsp;<strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">b&agrave;i giới thiệu c&ocirc;ng ty</em></strong>&nbsp;như &yacute;.</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Please kh&aacute;c biệt ngay từ lời giới thiệu doanh nghiệp!</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;"><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: transparent; overflow-wrap: break-word;">Boseda &ndash; Dịch vụ viết b&agrave;i giới thiệu c&ocirc;ng ty tr&ecirc;n to&agrave;n quốc</strong></em></p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Li&ecirc;n hệ th&ocirc;ng tin:</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Email: dung.boseda@gmail.com</p>
<p style="box-sizing: border-box; margin: 0px 0px 25px; padding: 0px; border: 0px; outline: 0px; font-size: 16px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; overflow-wrap: break-word; line-height: 1.8em; color: #414141; font-family: Roboto, \'Helvetica Neue\', Helvetica, Arial, sans-serif;">Điện thoại: 0979 560 552</p>',
                'image' => NULL,
                'slug' => 'user_guide',
                'meta_description' => NULL,
                'status' => 'ACTIVE',
                'created_at' => '2021-10-08 13:08:02',
                'updated_at' => '2021-10-09 14:42:29',
            ),
            3 => 
            array (
                'id' => 5,
                'author_id' => 1,
                'title' => 'Khoa hoc',
                'excerpt' => NULL,
                'body' => '<p><span style="color: #023ca1; font-family: \'Open Sans\', sans-serif; font-size: 22px; font-weight: bold;">CHƯƠNG TR&Igrave;NH LAN TỎA TRI THỨC</span><br style="color: #023ca1; font-family: \'Open Sans\', sans-serif; font-size: 22px; font-weight: bold;" /><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;">"GIỚI THIỆU BẠN B&Egrave; - NHẬN QU&Agrave; VUI VẺ"</span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="color: #005085; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px;">Chương tr&igrave;nh d&agrave;nh cho c&aacute;c Kh&aacute;ch h&agrave;ng c&aacute; nh&acirc;n đăng k&yacute; sử dụng THANH GIANG E-LEARNING (CHƯƠNG TR&Igrave;NH HỌC TẬP HO&Agrave;N TO&Agrave;N MIỄN PH&Iacute;)</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="color: #005085; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px;">Với người giới thiệu: Mỗi Kh&aacute;ch h&agrave;ng c&aacute; nh&acirc;n sẽ c&oacute; m&atilde; giới thiệu l&agrave; số điện thoại di động đăng k&yacute; sử dụng THANH GIANG E-LEARNING của ch&iacute;nh c&aacute; nh&acirc;n đ&oacute;. C&aacute; nh&acirc;n giới thiệu sẽ được tặng 10.000 POINT nếu giới thiệu sử dụng th&agrave;nh c&ocirc;ng THANH GIANG E-LEARNING đối với 01 Kh&aacute;ch h&agrave;ng mới (kh&ocirc;ng giới hạn số lần giới thiệu).</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="color: #005085; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px;">C&aacute; nh&acirc;n người giới thiệu c&oacute; thể được &aacute;p dụng thưởng nhiều lần, t&ugrave;y v&agrave;o số người m&agrave; họ giới thiệu th&agrave;nh c&ocirc;ng.</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="color: #005085; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px;">Với người được giới thiệu: Với mỗi c&aacute; nh&acirc;n được giới thiệu thực hiện đăng k&yacute; t&agrave;i khoản học tập tr&ecirc;n THANH GIANG E-LEARNING , nhập th&agrave;nh c&ocirc;ng m&atilde; code giới thiệu (số điện thoại của người giới thiệu) sẽ nhận được 10.000 POINT với vai tr&ograve; l&agrave; người được giới thiệu (sau đ&oacute; cũng sẽ c&oacute; quyền đi giới thiệu tiếp bạn mới v&agrave; nhận thưởng)</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="color: #015c8a; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px; font-weight: 400;">❖ POINT sẽ được cộng dồn để quy đổi th&agrave;nh gi&aacute; trị tương ứng v&agrave; được sử dụng khi đăng k&yacute; c&aacute;c dịch vụ kh&aacute;c của THANH GIANG như: du học c&aacute;c nước (Nhật, H&agrave;n, Canada, Mỹ, Anh, &Uacute;c, Đức,&hellip;) hoặc Xuất khẩu lao động Nhật (Kỹ sư &ndash; nh&acirc;n vi&ecirc;n, Kỹ năng đặc định, Thực tập sinh)</span><br style="color: #015c8a; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px; font-weight: 400;" /><span style="color: #015c8a; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px; font-weight: 400;">VD: giới thiệu 100 bạn th&igrave; tổng Point được nhận l&agrave; 1.000.000 Point, tương ứng với 1.000.000 VND v&agrave; được sử dụng khi tham gia c&aacute;c dịch vụ của THANH GIANG (Kh&ocirc;ng quy đổi tiền mặt)</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="color: #015c8a; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px; font-weight: 400;">❖ POINT được ph&eacute;p chuyển nhượng cho người kh&aacute;c sử dụng.</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="color: #015c8a; font-family: \'Source Sans Pro\', sans-serif; font-size: 14px; font-weight: 400;">❖ POINT c&oacute; gi&aacute; trị cộng dồn v&agrave; sử dụng trong v&ograve;ng 3 năm.</span></span></p>',
                'image' => NULL,
                'slug' => 'khoa-hoc',
                'meta_description' => NULL,
                'status' => 'INACTIVE',
                'created_at' => '2021-10-11 12:59:45',
                'updated_at' => '2021-10-11 13:21:22',
            ),
            4 => 
            array (
                'id' => 6,
                'author_id' => 1,
                'title' => 'Chương trình giới thiệu',
                'excerpt' => NULL,
                'body' => '<p><span style="color: #023ca1; font-family: \'Open Sans\', sans-serif; font-size: 22px; font-weight: bold;">CHƯƠNG TR&Igrave;NH THU NHẬP HẤP DẪN</span><br style="color: #023ca1; font-family: \'Open Sans\', sans-serif; font-size: 22px; font-weight: bold;" /><span style="color: #023ca1; font-family: \'Open Sans\', sans-serif; font-size: 22px; font-weight: bold;">GIỚI THIỆU BẠN THAM GIA C&Aacute;C&nbsp;</span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;">DỊCH VỤ TƯ VẤN DU HỌC - XKLĐ - GIỚI THIỆU NH&Acirc;N SỰ CỦA THANH GIANG</span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: Roboto, sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #005085; text-decoration-line: underline;">Bước 1:</span><span style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;">&nbsp;Nếu c&oacute; bạn b&egrave;, người th&acirc;n quan t&acirc;m t&igrave;m hiểu du học (Nhật, H&agrave;n, Anh, &Uacute;c, Mỹ, Canada, Singapore, Đức,...) hoặc XKLĐ Nhật (Kỹ sư-nh&acirc;n vi&ecirc;n, Kỹ năng đặc định, Thực tập sinh,...) th&igrave; li&ecirc;n hệ với Thanh Giang theo li&ecirc;n hệ sau:</span><br style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;" /><span style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;">&nbsp; &nbsp;- Điện thoại: 0918 58 2233</span><br style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;" /><span style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;">&nbsp; &nbsp;- Email: water@thanhgiang.com.vn</span><br style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;" /><span style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;">&nbsp; &nbsp;- Face Book: https://www.facebook.com/duhoc.thanhgiang.com.vn/</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: Roboto, sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #005085; text-decoration-line: underline;">Bước 2:</span><span style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;"> Thanh Giang sẽ gửi hợp đồng hợp t&aacute;c với người giới thiệu</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: Roboto, sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #005085; text-decoration-line: underline;">Bước 3:</span><span style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;"> Thanh Giang cử đại diện tư vấn vi&ecirc;n hỗ trợ cho người giới thiệu v&agrave; người được giới thiệu c&aacute;c th&ocirc;ng tin chi tiết, cụ thể của từng chương tr&igrave;nh</span></span></p>
<p><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: bold; font-stretch: inherit; font-size: 22px; line-height: inherit; font-family: \'Open Sans\', sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #ff0068;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: Roboto, sans-serif; vertical-align: baseline; box-sizing: border-box; -webkit-font-smoothing: antialiased; color: #005085; text-decoration-line: underline;">Bước 4:</span><span style="color: #005085; font-family: Roboto, sans-serif; font-size: 13px;"> Người được giới thiệu đăng k&yacute; ch&iacute;nh thức c&aacute;c chương tr&igrave;nh th&igrave; người giới thiệu sẽ nhận được chế độ hoa hồng giới thiệu theo hợp đồng</span></span></p>',
                'image' => NULL,
                'slug' => 'chuong-trinh-gioi-thieu',
                'meta_description' => NULL,
                'status' => 'INACTIVE',
                'created_at' => '2021-10-11 13:00:19',
                'updated_at' => '2021-10-11 14:05:46',
            ),
        ));
        
        
    }
}